apiVersion: v1
kind: Secret
metadata:
  name: scrypt-backend-secrets
type: Opaque
data:
  priv-key-0: "Y1RIcnd5dEhRWE1pbVF4VGpXc29uUGtZUVdaTVhzSnM0dXhUdnhqbjgzeXN5RWlVQW1Qaw=="
  address-0: "bW9QSFFaOE1LbVU1dG9DV3F2dm5yS3BHOGt1QnFGdGp5VQ=="
  priv-key-1: "Y05CbXkzMTVSeFVremdXdTNyOVBKQ3JZWUdvOXBqeUY3VzRWQVkxdEFnUW12YTNoOFNEUg=="
  address-1: "bXZnWjVQaW9vckVZaHM5RzVybXByczlGSGd4R3R6Q3NRRw=="
  priv-key-2: "Y1BiRDluelVkRG1GRkFoWWpaZjd3amoxcHRXYzZLN0FtczliS05Lb1NwRlRjdnhwOGhxYg=="
  address-2: "bXd4NkR2TXR3ZmVjNWFlNHA0WFBTRlFhaFpXZmU3Q0h2ZQ=="
  db-host: "bG9jYWxob3N0"
  db-port: "MjcwMTc="
  db-name: "c2NyeXB0LWVjb21t"
