apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bux-server
    app: bux
    instance: bux-server
  name: bux-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bux-server
      app: bux
      instance: bux-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bux
        instance: bux-server
        app.kubernetes.io/name: bux-server
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: bux-server-env-configs
      containers:
        - name: bux-server
          image: buxorg/bux-server-unstable:v0.11.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: bux-server-env
          env:
            - name: BUX_DB_SQL_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: POSTGRES_USER
            - name: BUX_DB_SQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: POSTGRES_PASSWORD
            - name: BUX_DB_SQL_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: POSTGRES_DB
            - name: BUX_PAYMAIL_BEEF_PULSE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pulse-configuration
                  key: PULSE_HTTP_AUTH_TOKEN
          volumeMounts:
            - name: config-volume
              mountPath: /config
          ports:
            - containerPort: 3003
              name: web
              protocol: TCP
