apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: bux
    instance: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP
  selector:
    app: bux
    instance: postgres
