apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: bux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bux
  template:
    metadata:
      labels:
        app: bux
    spec:
      containers:
        - name: postgres
          image: postgres:15.2-alpine3.17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: pgdb
          envFrom:
            - configMapRef:
                name: postgres-configuration
          volumeMounts:
            - name: pv
              mountPath: /var/postgresql/data
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: postgres-pvc
