apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypt-mongo-pvc
  labels:
    app: scrypt-ecomm
    instance: scrypt-mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
