apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrypt-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:gignative-solutions/k8s-config.git
    targetRevision: HEAD
    path: apps/scrypt-ecomm/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
