apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypt-redis-pvc
  labels:
    app: scrypt-ecomm
    instance: scrypt-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
