apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
configMapGenerator:
- name: bux-server-env-configs
  files:
  - config.yaml
- name: bux-server-env
  behavior: replace
  literals:
  - BUX_CONFIG_FILE=/config/config.yaml
