apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-bux-wallet-demo
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-bux-wallet-demo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bux-wallet
    app.kubernetes.io/managed-by: kubectl
data:
  POSTGRES_DB: "bux-wallet"
  POSTGRES_USER: "bux-wallet"
  POSTGRES_PASSWORD: "postgres"
