apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:4chain-ag/k8s-config.git
    targetRevision: HEAD
    path: apps/pulse
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
