apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulse-ingress
  labels:
    app: pulse
spec:
  rules:
    - host: pulse.4chain.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pulse
                port:
                  name: web
