name: "[Reuse] build docker image for bux-server"
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  check-docker-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout k8s-config
        with:
          path: 'k8s-config'
      - uses: actions/checkout@v3
        name: checkout bux-server
        with:
          repository: BuxOrg/bux-server
          ref: ${{inputs.version}}
          fetch-depth: 1
          path: 'bux-server'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 4chainstudio/bux-server:${{inputs.version}}
          context: './bux-server'
