name: '[Manual] Build bux-console'
on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        type: string
        default: master
      version:
        description: Docker image version tag that will be created
        required: true
        type: string

jobs:
  build-bux-console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout bux-console
        with:
          repository: BuxOrg/bux-console
          ref: ${{inputs.revision}}
          fetch-depth: 1
          path: 'bux-console'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 4chainstudio/bux-console:${{inputs.version}}
          context: './bux-console'