name: '[Schedule] Prepare newest version of bux-server'
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-newest-version:
    uses: ./.github/workflows/check-bux-version.yml
  print-output:
    runs-on: ubuntu-latest
    needs: check-newest-version
    steps:
      - run: echo "BUX VERSION ${{ needs.check-newest-version.outputs.buxversion }}"
      - run: echo "DOCKER NOT FOUND ${{ needs.check-newest-version.outputs.dockerNotFound }}"
  build-docker:
    uses: ./.github/workflows/build-bux.yml
    needs: check-newest-version
    if: success() && needs.check-newest-version.outputs.dockerNotFound == 'true'
    secrets: inherit
    with:
      version: ${{ needs.check-newest-version.outputs.buxversion }}
  update-version-pr:
    needs: [ check-newest-version, build-docker ]
    if: success()
    uses: ./.github/workflows/update-bux-pr.yml
    secrets: inherit
    with:
      version: ${{ needs.check-newest-version.outputs.buxversion }}
