name: '[Manual] Build bux-server docker'
on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        type: string

jobs:
  build-docker:
    uses: ./.github/workflows/build-bux.yml
    secrets: inherit
    with:
      version: ${{ inputs.revision }}
  update-version-pr:
    needs: build-docker
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "update bux-server version"
        uses: ./.github/actions/update-version
        with:
          deployment_file: './apps/bux-server/bux/base/deployment.yml'
