name: '[Manual] Build bux-server docker'
on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        type: string

jobs:
  build-docker:
    uses: ./.github/workflows/build-bux.yml
    secrets: inherit
    with:
      version: ${{ inputs.revision }}
  update-version-pr:
    needs: build-docker
    if: success()
    uses: ./.github/workflows/update-bux-pr.yml
    secrets: inherit
    with:
      version: ${{ inputs.revision }}
