name: 'Update service versions'
on:
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3
      - name: "update bux-server version"
        uses: ./.github/actions/update-version
        with:
          deployment_file: './apps/bux-server/bux/base/deployment.yml'

      - name: "update pulse version"
        uses: ./.github/actions/update-version
        with:
          deployment_file: './apps/pulse/deployment.yml'

      - name: "update bux-wallet backend version"
        uses: ./.github/actions/update-version
        with:
          deployment_file: './apps/bux-wallet/backend/deployment.yml'
          dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME_4CHAIN }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN_4CHAIN }}
      - name: "update bux-wallet frontend version"
        uses: ./.github/actions/update-version
        with:
          deployment_file: './apps/bux-wallet/frontend/deployment.yml'
          dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME_4CHAIN }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN_4CHAIN }}
